### ISSUE TITLE
Can't see 802.11b compatible access points

### ISSUE THREAD

**Issue by sgtnoodle** [juanro49/rtl88x2ce-dkms#1]
There seems to be a bug common to all RTL* sources that prevents the driver from working with access points that support 802.11b rates.

There's a fix for a similar driver:

https://github.com/tomaspinho/rtl8821ce/commit/109257b97980b9294974db47df842eaa76932ed6

I just tried patching it in by hand and it solves the issue, so that's good!

**Comment by juanro49** [comment]
Thanks!! you can open a pull request?

**Comment by juanro49** [comment]
Issue fixed https://github.com/juanro49/rtl88x2ce-dkms/commit/5126bac2a965b873f310364676744adfefbeafed
